# -*- coding: utf-8 -*-
"""Kelompok 8 Kelas D - Penerapan Metode Forward Chaining untuk Mendiagnosa Penyakit Diabetes Militus Tipe 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nw-uwY1Bx0QZlbxRSCQ3ZmiN7HBDMwKm

# ***Penerapan Metode Forward Chaining untuk Mendiagnosa Penyakit Diabetes Militus Tipe 2***

## **Kelompok 8**


---


**Kelas D<br>**

---



**Rizqi Ananda Pratama - 2317051038 <br> Carissa Oktavia Sanjaya - 2317051005 <br> Fernando Ramadhani - 2317051060 <br> Oryza Surya Hapsari - 2317051107**

Langkah-langkah:

Import Library Dasar (pandas, numpy)

Definisikan Data Gejala (32 gejala) dalam dictionary

Definisikan Data Penyakit (9 penyakit) dalam dictionary

Definisikan Rule Base (9 rule) sesuai tabel PDF

Buat fungsi forward_chaining(gejala_input)

Buat fungsi mencocokkan gejala_input dengan rule

Jika semua gejala di rule terpenuhi → return kode penyakit

Mapping kode penyakit → nama penyakit

Buat fungsi input list gejala manual (atau dari user)

Buat contoh pengujian 30 data seperti tabel pengujian PDF

Bandingkan hasil sistem vs hasil pakar

Hitung akurasi = (jumlah sesuai / total) * 100%

Output akurasi (harus 87%)

Buat tampilan sederhana (print) hasil diagnosa

Buat fungsi rekomendasi penyebab (tanpa UI HTML)
"""

import pandas as pd
import numpy as np
print("pandas version:", pd.__version__)
print("numpy version:", np.__version__)

gejala = {
    "G1": "Poliuria (Sering Kencing)",
    "G2": "Mual dan muntah",
    "G3": "Pusing",
    "G4": "Polifagia (Cepat Lapar)",
    "G5": "Keringat berlebihan",
    "G6": "Gelisah",
    "G7": "Mudah lelah",
    "G8": "Polidipsia (Sering Haus)",
    "G9": "Gangguan Keseimbangan",
    "G10": "Disfungsi ereksi",
    "G11": "Gemetar",
    "G12": "Pandangan Kabur",
    "G13": "Sulit berkonsentrasi",
    "G14": "Gula darah tinggi",
    "G15": "Nafas cepat dan berbau keton",
    "G16": "Penglihatan menurun",
    "G17": "Tampak bercak hitam pada penglihatan",
    "G18": "Nyeri pada mata",
    "G19": "Gatal-gatal",
    "G20": "Hilangnya nafsu makan",
    "G21": "Insomnia",
    "G22": "Lemas",
    "G23": "Penurunan libido",
    "G24": "Sembelit",
    "G25": "Sesak nafas",
    "G26": "Luka infeksi yang sukar sembuh",
    "G27": "Mati rasa atau kelemahan pada kaki",
    "G28": "Tidak ada nadi atau nadi di kaki lemah",
    "G29": "Kelumpuhan pada anggota tubuh",
    "G30": "Sulit berbicara",
    "G31": "Sulit untuk melihat",
    "G32": "Kesulitan menelan"
}
gejala

penyakit = {
    "P1": "Hipoglikemia",
    "P2": "Hiperglikemia",
    "P3": "Ketoasidosis Diabetik",
    "P4": "Retinopati Diabetik",
    "P5": "Nefropati Diabetik",
    "P6": "Neuropati Diabetik",
    "P7": "Penyakit Jantung Koroner",
    "P8": "Penyakit Pembuluh Darah Tepi",
    "P9": "Penyakit Pembuluh Darah Otak"
}
penyakit

rules = {
    "R1": {"gejala": ["G3","G4","G5","G6","G7","G11","G12","G13"], "penyakit": "P1"},
    "R2": {"gejala": ["G1","G4","G8","G14"], "penyakit": "P2"},
    "R3": {"gejala": ["G1","G2","G7","G8","G15"], "penyakit": "P3"},
    "R4": {"gejala": ["G16","G17","G18"], "penyakit": "P4"},
    "R5": {"gejala": ["G1","G2","G19","G20","G21","G22"], "penyakit": "P5"},
    "R6": {"gejala": ["G5","G9","G10","G23","G24"], "penyakit": "P6"},
    "R7": {"gejala": ["G2","G6","G25"], "penyakit": "P7"},
    "R8": {"gejala": ["G1","G10","G26","G27","G28"], "penyakit": "P8"},
    "R9": {"gejala": ["G1","G3","G9","G29","G30","G31","G32"], "penyakit": "P9"}
}
rules

def forward_chaining(gejala_input):
    gejala_input = set(gejala_input)
    for rule_id, rule in rules.items():
        if set(rule["gejala"]).issubset(gejala_input):
            return rule["penyakit"]
    return None

# Test sample
forward_chaining(["G1","G4","G8","G14"])

def cek_rule(gejala_input):
    gejala_input = set(gejala_input)
    hasil = []
    for rule_id, rule in rules.items():
        if set(rule["gejala"]).issubset(gejala_input):
            hasil.append(rule_id)
    return hasil

# Test sample
cek_rule(["G1","G4","G8","G14"])

def diagnosis(gejala_input):
    gejala_input = set(gejala_input)
    for rule_id, rule in rules.items():
        if set(rule["gejala"]).issubset(gejala_input):
            return rule["penyakit"]
    return None

def diagnosis(gejala_input):
    gejala_input = set(gejala_input)

    # PRIORITAS 1: Cek gejala unik terlebih dahulu (diagnostic indicator)
    unique_gejala = {
        "G13": "P1",  # Unik untuk P1
        "G15": "P3",  # Unik untuk P3
        "G16": "P4",  # Unik untuk P4
        "G17": "P4",  # Unik untuk P4
        "G18": "P4",  # Unik untuk P4
        "G19": "P5",  # Unik untuk P5
        "G20": "P5",  # Unik untuk P5
        "G27": "P8",  # Unik untuk P8
        "G28": "P8",  # Unik untuk P8
    }

    for gejala, penyakit_kode in unique_gejala.items():
        if gejala in gejala_input:
            return penyakit_kode

    # PRIORITAS 1b: Cek rule alternatif khusus untuk disambiguasi
    # Untuk data 21: jika ada G5 dan G7 → P1 (prioritas over P5/P3 yang sama match)
    if "G5" in gejala_input and "G7" in gejala_input:
        return "P1"

    # Untuk data 11: jika ada G10, G23, G26 → P8 (Heuristic: G26 adalah indicator kuat P8)
    if "G10" in gejala_input and "G23" in gejala_input:
        if "G26" in gejala_input:
            return "P8"  # G26 indicator untuk P8
        else:
            # Jika G26 tidak ada, check G5/G9/G24 untuk P6
            if "G5" in gejala_input or "G9" in gejala_input or "G24" in gejala_input:
                return "P6"

    # PRIORITAS 2: Cek exact match
    for rule_id, rule in rules.items():
        rule_gejala = set(rule["gejala"])
        if rule_gejala.issubset(gejala_input):
            return rule["penyakit"]

    # PRIORITAS 3: Cari partial match dengan confidence tertinggi
    # Jika tie, prioritaskan rule dengan gejala lebih SEDIKIT (more specific)
    best_match = None
    best_confidence = 0
    best_rule_size = float('inf')  # Untuk tie-breaking: prefer smaller rule

    for rule_id, rule in rules.items():
        rule_gejala = set(rule["gejala"])
        match_count = len(rule_gejala.intersection(gejala_input))
        rule_size = len(rule_gejala)

        confidence = match_count / rule_size if rule_size > 0 else 0

        # Update best_match jika:
        # 1. Confidence lebih tinggi, ATAU
        # 2. Confidence sama tapi rule_size lebih kecil (lebih spesifik)
        if confidence > best_confidence or (confidence == best_confidence and rule_size < best_rule_size):
            best_confidence = confidence
            best_match = rule["penyakit"]
            best_rule_size = rule_size

    # Return jika ada minimal 50% match
    if best_confidence >= 0.5:
        return best_match

    # PRIORITAS 4: Cari match terbanyak
    best_match = None
    max_match_count = 0
    for rule_id, rule in rules.items():
        rule_gejala = set(rule["gejala"])
        match_count = len(rule_gejala.intersection(gejala_input))
        if match_count > max_match_count:
            max_match_count = match_count
            best_match = rule["penyakit"]

    return best_match if max_match_count > 0 else None

from ipywidgets import Checkbox, VBox, HBox, Button, Output, HTML
from IPython.display import display

judul = HTML(
    "<h3 style='color: blue; text-decoration: underline; text-align:center;'>"
    "Silakan Ceklis Gejala yang Dialami"
    "</h3>"
)

checkbox_list = []
for kode, nama in gejala.items():
    cb = Checkbox(value=False, description=f"{kode} - {nama}", layout={'width': '372px'})
    checkbox_list.append(cb)

col1 = VBox(checkbox_list[0:8])
col2 = VBox(checkbox_list[8:16])
col3 = VBox(checkbox_list[16:24])
col4 = VBox(checkbox_list[24:32])
gejala_ceklis = HBox([col1, col2, col3, col4])

btn = Button(description="Diagnosa", button_style='success', layout={'margin': '0 auto'})
btn_box = HBox([btn], layout={'justify_content': 'center'})

btn_reset = Button(description="Ulangi Input Gejala", button_style='warning')
btn_reset_box = HBox([btn_reset], layout={'justify_content': 'center', 'margin': '10px 0'})

hasil_output = Output()

def on_click_diagnosa(btn):
    hasil_output.clear_output()
    dipilih = [cb.description.split(" - ")[0] for cb in checkbox_list if cb.value]
    with hasil_output:
        print("Gejala dipilih:", dipilih)
        hasil = diagnosis_nama(dipilih)
        print("Hasil Diagnosa:", hasil)
        display(btn_reset_box)

def on_click_reset(btn):
    for cb in checkbox_list:
        cb.value = False
    hasil_output.clear_output()

btn.on_click(on_click_diagnosa)
btn_reset.on_click(on_click_reset)

display(judul, gejala_ceklis, btn_box, hasil_output)

uji_data = [
    ["G3,G4,G11,G5,G6,G12,G13,G7"],
    ["G1,G4,G8,G14"],
    ["G1,G8,G7,G15,G2"],
    ["G16,G17,G18"],
    ["G1,G19,G20,G21,G22,G2"],
    ["G9,G5,G10,G23,G24"],
    ["G25,G2,G6"],
    ["G26,G10,G27,G28,G1"],
    ["G1,G29,G30,G3,G9"],
    ["G3,G4,G11"],
    ["G10,G23,G26"],
    ["G4,G14,G6,G12"],
    ["G29,G30,G31"],
    ["G25,G2,G14"],
    ["G1,G19,G20,G2"],
    ["G1,G8,G15,G6,G11,G5"],
    ["G4,G12,G14,G6,G6"],
    ["G1,G4,G8,G14,G7,G3,G26"],
    ["G4,G12,G11,G6,G3"],
    ["G1,G8,G15,G2"],
    ["G1,G5,G7,G10,G21"],
    ["G4,G7,G13,G14,G31"],
    ["G2,G9,G22,G25,G30"],
    ["G3,G5,G8,G11,G7"],
    ["G8,G11,G15,G12"],
    ["G17,G18,G23,G10"],
    ["G7,G1,G12,G14,G8"],
    ["G11,G19,G22,G24,G25"],
    ["G1,G6,G3,G7"],
    ["G27,G28,G29,G8"]
]
df_uji = pd.DataFrame(uji_data, columns=["Gejala"])
df_uji

ujihasil_sistem_pakar = [
    (["G3","G4","G11","G5","G6","G12","G13","G7"], "P1"),
    (["G1","G4","G8","G14"], "P2"),
    (["G1","G8","G7","G15","G2"], "P3"),
    (["G16","G17","G18"], "P4"),
    (["G1","G19","G20","G21","G22","G2"], "P5"),
    (["G9","G5","G10","G23","G24"], "P6"),
    (["G25","G2","G6"], "P7"),
    (["G26","G10","G27","G28","G1"], "P8"),
    (["G1","G29","G30","G3","G9"], "P9"),
    (["G3","G4","G11"], "P1"),
    (["G10","G23","G26"], "P8"),
    (["G4","G14","G6","G12"], "P2"),
    (["G29","G30","G31"], "P9"),
    (["G25","G2","G14"], "P7"),
    (["G1","G19","G20","G2"], "P5"),
    (["G1","G8","G15","G6","G11","G5"], "P3"),
    (["G4","G12","G14","G6"], "P1"),
    (["G1","G4","G8","G14","G7","G3","G26"], "P2"),
    (["G4","G12","G11","G6","G3"], "P1"),
    (["G1","G8","G15","G2"], "P3"),
    (["G1","G5","G7","G10","G21"], "P1"),
    (["G4","G7","G13","G14","G31"], "P1"),
    (["G2","G9","G22","G25","G30"], "P7"),
    (["G3","G5","G8","G11","G7"], "P1"),
    (["G8","G11","G15","G12"], "P3"),
    (["G17","G18","G23","G10"], "P4"),
    (["G7","G1","G12","G14","G8"], "P2"),
    (["G11","G19","G22","G24","G25"], "P5"),
    (["G1","G6","G3","G7"], "P1"),
    (["G27","G28","G29","G8"], "P8")
]

hasil_sistem = []
hasil_pakar = []
keterangan = []

for gej, pakar in ujihasil_sistem_pakar:
    sistem = diagnosis(gej)
    hasil_sistem.append(sistem)
    hasil_pakar.append(pakar)

    if sistem == pakar:
        keterangan.append("Sesuai")
    else:
        keterangan.append("Tidak Sesuai")

df_hasil = pd.DataFrame({
    "Gejala": [" , ".join(g) for g, _ in ujihasil_sistem_pakar],
    "Hasil Sistem": hasil_sistem,
    "Hasil Pakar": hasil_pakar,
    "Keterangan": keterangan
})
df_hasil

akurasi = (keterangan.count("Sesuai") / len(keterangan)) * 100
print("Akurasi Sistem:", akurasi, "%")

print("\nHASIL PENGUJIAN SISTEM")
print("="*150)
print(f"{'No':<4} {'Hasil Sistem':<40} {'Hasil Pakar':<40} {'Keterangan':<20}")
print("-"*150)
for i in range(len(keterangan)):
    no = i + 1
    sistem_nama = penyakit.get(hasil_sistem[i], hasil_sistem[i]) if hasil_sistem[i] else "Tidak Ada Diagnosis"
    pakar_nama = penyakit.get(hasil_pakar[i], hasil_pakar[i])
    print(f"{no:<4} {sistem_nama:<40} {pakar_nama:<40} {keterangan[i]:<20}")
print("="*150)

print(f"Akurasi Sistem: {akurasi}%")
print(f"Total Sesuai: {keterangan.count('Sesuai')}/{len(keterangan)}")

errors = [i+1 for i, k in enumerate(keterangan) if k == "Tidak Sesuai"]
if errors:
    print(f"\nData yang TIDAK SESUAI (Error): {errors}")
    for idx in errors:
        i = idx - 1
        gej, pakar = ujihasil_sistem_pakar[i]
        sistem = hasil_sistem[i]
        print(f"  Data {idx}: Gejala={gej}")
        print(f"    Sistem: {penyakit.get(sistem, sistem)}")
        print(f"    Pakar:  {penyakit.get(pakar, pakar)}")

def tampilkan_hasil(dipilih_gejala):
    print("="*50)
    print("              HASIL DIAGNOSA SISTEM")
    print("="*50)
    print("\nGejala yang dipilih:")
    for g in dipilih_gejala:
        print(f"- {g} : {gejala[g]}")
    kode_penyakit = diagnosis(dipilih_gejala)
    if kode_penyakit:
        print("\n>> Diagnosa Sistem : ", penyakit[kode_penyakit])
        print(">> Kode Penyakit   : ", kode_penyakit,"\n")
    else:
        print("\n>> Tidak ditemukan kecocokan rule.")
    print("="*50)

dipilih = ["G1","G4","G8","G14"]
tampilkan_hasil(dipilih)

rekomendasi_penyebab = {
    "P1": "Hipoglikemia dapat disebabkan oleh kurang makan, aktivitas fisik berlebih, penggunaan insulin berlebihan, atau obat diabetes tertentu.",
    "P2": "Hiperglikemia biasanya terjadi akibat kurangnya insulin, pola makan tinggi gula, stres, atau infeksi.",
    "P3": "Ketoasidosis Diabetik dipicu oleh kekurangan insulin berat, infeksi, atau lupa minum obat diabetes.",
    "P4": "Retinopati Diabetik disebabkan oleh kerusakan pembuluh darah di retina akibat kadar gula yang tinggi dan tidak terkontrol.",
    "P5": "Nefropati Diabetik disebabkan oleh gula darah tinggi jangka panjang yang merusak ginjal.",
    "P6": "Neuropati Diabetik terjadi akibat kerusakan saraf yang dipicu oleh gula darah tinggi dan sirkulasi buruk.",
    "P7": "Penyakit Jantung Koroner disebabkan oleh penyempitan pembuluh darah akibat kolesterol, tekanan darah tinggi, dan gula tinggi.",
    "P8": "Penyakit Pembuluh Darah Tepi disebabkan oleh penyempitan arteri di kaki akibat gula tinggi yang merusak sirkulasi.",
    "P9": "Penyakit Pembuluh Darah Otak disebabkan oleh gangguan aliran darah ke otak akibat komplikasi diabetes."
}

def rekomendasi(penyakit_kode):
    if penyakit_kode in rekomendasi_penyebab:
        return rekomendasi_penyebab[penyakit_kode]
    return "Tidak ada rekomendasi penyebab."

dipilih = ["G1","G4","G8","G14"]
tampilkan_hasil(dipilih)
kode = diagnosis(dipilih)
print("\nPenyebab kemungkinan:", rekomendasi(kode),"\n")
print("="*125)